In [5]:
import numpy as np 
import composite as cp 
A = cp.layer('HT3/5224')
A.get_status()

name:	HT3/5224
t:	 0.000125
angle:	 0
Q:	 [[1.41061488e+11 3.03282199e+09 0.00000000e+00]
 [3.03282199e+09 8.66520567e+09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.00000000e+09]]
S:	 [[ 7.14285714e-12 -2.50000000e-12  0.00000000e+00]
 [-2.50000000e-12  1.16279070e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.00000000e-10]]
Q_:	 [[1.41061488e+11 3.03282199e+09 0.00000000e+00]
 [3.03282199e+09 8.66520567e+09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.00000000e+09]]
S_:	 [[ 7.14285714e-12 -2.50000000e-12  0.00000000e+00]
 [-2.50000000e-12  1.16279070e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.00000000e-10]]


In [11]:
A.set_angle_degree(45)
A.get_status()

name:	HT3/5224
t:	 0.000125
angle:	 0.7853981633974483
Q:	 [[1.41061488e+11 3.03282199e+09 0.00000000e+00]
 [3.03282199e+09 8.66520567e+09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.00000000e+09]]
S:	 [[ 7.14285714e-12 -2.50000000e-12  0.00000000e+00]
 [-2.50000000e-12  1.16279070e-10  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.00000000e-10]]
Q_:	 [[4.39480843e+10 3.39480843e+10 3.30990705e+10]
 [3.39480843e+10 4.39480843e+10 3.30990705e+10]
 [3.30990705e+10 3.30990705e+10 3.59152623e+10]]
S_:	 [[ 7.96054817e-11 -2.03945183e-11 -5.45681063e-11]
 [-2.03945183e-11  7.96054817e-11 -5.45681063e-11]
 [-5.45681063e-11 -5.45681063e-11  1.28421927e-10]]


In [10]:
def RigidityCal(Q,a):
    """
    输入：Q(GPa),a(°)
    输出：某一角度下的Q

    """
    a = a*np.pi/180
    Q11,Q22,Q12,Q66 = Q[0,0],Q[1,1],Q[0,1],Q[2,2]
    m,n = np.cos(a),np.sin(a)
    Q_11 = np.power(m,4)*Q11 + np.power(n,4)*Q22 + 2*m*m*n*n*Q12 + 4*m*m*n*n*Q66
    Q_22 = np.power(n,4)*Q11 + np.power(m,4)*Q22 + 2*m*m*n*n*Q12 + 4*m*m*n*n*Q66
    Q_12 = m*m*n*n*Q11 + m*m*n*n*Q22 + (np.power(m,4)+np.power(n,4))*Q12 - 4*m*m*n*n*Q66
    Q_66 = m*m*n*n*Q11 + m*m*n*n*Q22 - 2*m*m*n*n*Q12 + (m*m-n*n)*(m*m-n*n)*Q66
    Q_16 = m*m*m*n*Q11 - m*n*n*n*Q22 + (m*n*n*n-m*m*m*n)*Q12 + 2*(m*n*n*n-m*m*m*n)*Q66
    Q_26 = m*n*n*n*Q11 - m*m*m*n*Q22 + (m*m*m*n-m*n*n*n)*Q12 + 2*(m*m*m*n-m*n*n*n)*Q66

    Q_a = np.mat([[Q_11,Q_12,Q_16],[Q_12,Q_22,Q_26],[Q_16,Q_26,Q_66]])
    return Q_a

Q=A.Q
Q45 = np.mat(RigidityCal(Q,60))
Q45

matrix([[1.85778294e+10, 2.62192687e+10, 1.52779346e+10],
        [2.62192687e+10, 8.47759704e+10, 4.20513372e+10],
        [1.52779346e+10, 4.20513372e+10, 2.81864468e+10]])