In [1]:
import numpy as np 
import composite as cp 

In [3]:
A = cp.layer('HT3/5224')
A.set_angle_degree(45)
B = cp.layer('HT3/5224')
B.set_angle_degree(-45)
C = cp.layer('HT3/5224')
C.set_angle_degree(0)

comp = cp.compound([A,B,C,C],status='S')
comp.h
comp.t
comp.A
comp.D
comp.strain_cal(Mx=20,outermost=True)

array([[[ 0.00363294],
        [-0.00270049],
        [-0.00027083]]])

In [4]:
a=np.zeros([3,3])
b=np.array(range(9)).reshape([3,3])
np.r_[a,b],np.c_[a,b]

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([[0., 0., 0., 0., 1., 2.],
        [0., 0., 0., 3., 4., 5.],
        [0., 0., 0., 6., 7., 8.]]))